name: Build and deploy ASP.Net Core app to Azure Web App - ag-customs-report-uat

on:
  push:
    branches:
      -uat
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'ag-customs-report-uat'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISHPROFILE_UAT }}
        package: ./dist
